### ISSUE TITLE
Translate in English

### ISSUE THREAD

**Issue by HassanUsman** [hencoder/PracticeLayout1#1]
can you make a readme in English for English users?

**Comment by rengwuxian** [comment]
That won't be a lot of work, but...

This repo is a practice project of a tutorial on my blog. I doubt whether you'll get the concept behind the code implementation (which is much more important than the code) if you only read an English version of the README (Or even plus an English version of code comments).

Or what do you think?

FYI: The article for this repo on my blog: http://hencoder.com/ui-2-1 (There could be some access issue due to the Great Fire Wall of China, I'm not sure.)

**Comment by HassanUsman** [comment]
Thanks try to add English comments and Readme also.
